//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyJLSV7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleFactura()
        {
            this.Facturas = new HashSet<Facturas>();
        }
    
        public int Codigo { get; set; }
        public int Cantidad { get; set; }
        public string Valor { get; set; }
        public int Codigoplato { get; set; }
    
        public virtual Plato Plato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas> Facturas { get; set; }
    }
}
