//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyJLSV7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas()
        {
            this.Persona = new HashSet<Persona>();
        }
    
        public int Facturas1 { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> Codigo { get; set; }
        public Nullable<int> Numeropago { get; set; }
        public Nullable<int> idProducto { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        public virtual DetalleFactura DetalleFactura { get; set; }
        public virtual Formapago Formapago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Persona> Persona { get; set; }
    }
}
