//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyJLSV7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int idPersona { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Tipodocumento { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string Tiporol { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<int> Facturas { get; set; }
    
        public virtual Facturas Facturas1 { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
